server:
  port: 8750
spring:
  rabbitmq:
    host: 192.168.2.2
    port: 5672
    username: admin
    password: 123
    virtual-host: /
    publisher-confirms: true
    publisher-returns: true
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: manual
        retry:
          enabled: true
          max-attempts: 5
          initial-interval: 5000
          max-interval: 5000
          multiplier: 5
weixin_notify_url: http://245t2920v7.wicp.vip/weixin_callback/notifyWeiXinPay
alipay_notify_url: http://245t2920v7.wicp.vip/alipay_callback/notifyAliPay
jlpay_notify_url: http://245t2920v7.wicp.vip/japay_callback/notifyJlPay
name: "test2"
